# Official repos only go up to bookworm, not trixie
- name: Add Tailscale repository
  ansible.builtin.deb822_repository:
    name: tailscale
    types: deb
    uris: https://pkgs.tailscale.com/stable/debian
    suites: trixie
    components: main
    signed_by: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present

- name: Check if Tailscale is already connected
  ansible.builtin.command: tailscale status
  register: tailscale_status
  changed_when: false
  failed_when: false

- name: Connect to Tailscale network
  ansible.builtin.command: >
    tailscale up
    --authkey="{{ tailscale_authkey }}"
    --ssh
    --accept-dns
    --hostname="{{ inventory_hostname }}"
  when: tailscale_status.rc != 0
  register: tailscale_up_result
  changed_when: tailscale_up_result.rc != 0

- name: Display Tailscale connection result
  ansible.builtin.debug:
    var: tailscale_up_result.stdout_lines
  when: tailscale_status.rc != 0

- name: DigitalOcean DNS and netplan config
  ansible.builtin.include_tasks: tasks/tailscale_network_do.yml
  when: "'digitalocean' in group_names"

- name: Proxmox DNS and network config
  ansible.builtin.include_tasks: tasks/tailscale_network_proxmox.yml
  when: "'proxmox' in group_names"

# Remove the reference to a public IP for this machine in our inventory.
# This means that Ansible will connect to machines via Tailscale hostname,
# using Tailscale SSH. We don't need to manage any SSH keys for that.
- name: Update inventory file to use Tailscale hostname
  become: false
  ansible.builtin.lineinfile:
    path: "{{ playbook_dir }}{{ hostfile_path }}"
    # Use fancy regex to split our line into \1, the target section, and \2
    # then replace only the ansible_host var.
    regexp: "^({{ inventory_hostname }} )ansible_host=\\S+(.*)"
    line: "\\1ansible_host={{ inventory_hostname }}\\2"
    backrefs: true
    backup: true
  delegate_to: localhost
