[nats]
# alias / inventory_hostname; most vars. should live elsewhere
aws-small-1 ansible_host=hostname

[timescale]
gcp-medium-2 ansible_host=hostname2

[collectors]
hetzner-medium-3 ansible_host=hostname3

# Run the archiver on the same machine as TimescaleDB, no need to separate
[archivers]
gcp-medium-2 ansible_host=hostname2

[proxmox]
indexer ansible_host=indexer

[baremetal]
# Custom hostname in case we're repurposing a machine that already had
# some partial setup. Running the Tailscale playbook will overwrite this.
sparc-benchbox ansible_host=sparc.local

[all:vars]
ansible_python_interpreter=/usr/bin/python3
# Before playbook tasks, we connect to the machine to 'gather facts'; doing
# that with the local username will fail
